### ISSUE TITLE
No demo project added. Please add a demo project!

### ISSUE THREAD

**Issue by galfaroth** [konstantinpavlikhin/KSPAutomaticHeightCalculationTableCellView#1]
No demo project added. Please add a demo project!

**Comment by pengwj** [comment]
Please add a demo project! @konstantinpavlikhin

**Comment by konstpavlone** [comment]
Guys, I am really sorry for the long time it took me to implement this! 🙏🏻

I thought that the `KSPAutomaticHeightCalculationTableCellView` is so simple that it doesn't need a dedicated sample app, because the size of the latter would be an order of magnitude larger than the initial class.

Anyway, now we have a full-featured demo application. Give it a try.
